# Generated by Django 3.1.1 on 2020-09-21 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('crm', models.CharField(max_length=4)),
                ('email', models.EmailField(blank=True, max_length=250, null=True)),
                ('telefone', models.CharField(blank=True, max_length=11, null=True)),
                ('especialidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialidades.especialidade')),
            ],
            options={
                'verbose_name': 'medico',
                'verbose_name_plural': 'medicos',
            },
        ),
    ]
